//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotationSolver.SourceGenerators.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotationSolver.SourceGenerators.Properties.ContentType", typeof(ContentType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///DutyRoulette = 1,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Dungeons = 2,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Guildhests = 3,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Trials = 4,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Raids = 5,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///PvP = 6,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///QuestBattles = 7,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///FatEs = 8,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///TreasureHunt = 9,
        ////// &lt;summary&gt;
        ////// 
        ////// &lt;/summary&gt;
        ///Levequ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
